config/routes.rb
Rails.application.routes.draw do
  
  resources :pins do
    resource :like , module: :pins
  end

  devise_for :users, :controllers => { 
      registrations: 'registrations' 
    } 
  
  root "pins#index"
end

app/models/like.rb
class Like < ActiveRecord::Base
	belongs_to :user
	belongs_to :pin
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user
	has_many :likes

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
    validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :profile_name , presence: true, 
                uniqueness: true

  has_many :pins

  has_many :likes

  def likes?(pin)
  	pin.likes.where(user_id: id).any?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins/likes_controller.rb
class Pins::LikesController < ApplicationController

	before_action :authenticate_user!
	before_action :set_pin

	def create
		@pin.likes.where(user_id: current_user.id).first_or_create

		respond_to do |format|
			format.html {redirect_to @pin}
			format.js
		end
	end

	def destroy
		@pin.likes.where(user_id: current_user.id).destroy_all

		respond_to do |format|
			format.html {redirect_to @pin}
			format.js
		end
	end


	private

	def set_pin
		@pin = Pin.find(params[:pin_id])
	end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
	before_action :find_pin , only: [:show , :edit, :update , :destroy]

	def index
		@pins = Pin.all.order("created_at DESC")
	end

	def show
	end

	def new
	 @pin = current_user.pins.build
	end

	def create
		@pin = current_user.pins.build(pin_params)

		if @pin.save
			redirect_to @pin , notice: "You're post is done"
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @pin.update(pin_params)
			redirect_to @pin, notice: "You update that post!"
		else
			render 'edit'
		end
	end

	def destroy
		@pin.destroy
		redirect_to root_path
	end

	private

		def pin_params
			params.require(:pin).permit(:title, :description , :image)
		end

		def find_pin
			@pin = Pin.find(params[:id])
		end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params 
    params.require(:user).permit(
      :user_id,
      :profile_name,
      :email, 
      :password, 
      :password_confirmation
    ) 
  end

  def account_update_params 
    params.require(:user).permit(   
      :email, 
      :profile_name,
      :password, 
      :password_confirmation, 
      :current_password
      ) 
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feedgia2</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path , class: "navbar-brand" do %>
      	Feedgia<b id="brandnav">2</b>
      <% end %>
     </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
      	<li><%= link_to "New Post"  , new_pin_path %></li>
        <li><%= link_to "Account" , edit_user_registration_path %></li>
      	<li><%= link_to 'Sign out' , destroy_user_session_path , method: :delete %></li>
      	<% else %>
        <li><%= link_to 'Sign Up' , new_user_registration_path %></li>
        <li><%= link_to 'Log In'  , user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <p id="notice"><%= notice %></p>
	<%= yield %>
</div>

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { multipart: true } do |f|
	- if @pin.errors.any?
		#errors
	%h2
	= pluralize(@pin.errors.count , "error")
	Prevented this Pin from saving
	%ul
	- @pin.errors.full_messages.each do |msg|
		%li= msg

	.form_group
	= f.file_field :image , class: "form-control"
	%br
	.form_group
	= f.input :title, input_html: { class: "form-control" }
	%br
	.form_group
	= f.input :description , input_html: { class: "form-control" }
	%br
	= f.button :submit , class: "btn btn-primary"

app/views/pins/_likers.html.erb
<% @pin.likes.each do |like| %>
	<%= like.user.profile_name %>
<% end %>

app/views/pins/_likes.html.erb
<% if user_signed_in? && current_user.likes?(pin) %>

	<%= link_to pin_like_path(pin), method: :delete, remote: true do%>
	<button type="button" class="btn btn-success btn-md" >
		<i class="fa fa-thumbs-up" style="font-size:1.2em"></i>
		<span class="badge"><%= pin.likes.count %></span>
	</button>
		
	<% end %>

<% else %>

	<%= link_to pin_like_path(pin), method: :post, remote: true do%>
	<button type="button" class="btn btn-default btn-md">
		<i class="fa fa-thumbs-down" style="font-size:1.2em"></i>
		<span class="badge"><%= pin.likes.count %></span>
	</button>
	
	<% end %>

<% end %>

app/views/pins/edit.html.haml
.col-md-6.col-md-offset-3
	%h1 Edit Post
	= link_to image_tag @pin.image.url(:medium)
	= render 'form'
	= link_to 'Back' , pin_path

app/views/pins/index.html.haml
#pins.transitions-enabled
	- @pins.each do |pin|
		.box.panel.panel-default
			= link_to (image_tag pin.image.url), pin
			%h2= link_to pin.title, pin
			%p.user
				Posted by
				= pin.user.profile_name
			%p{:id => "pin_#{pin.id}_likes"}= render partial: "likes", locals: {pin: pin}

	

app/views/pins/likes/create.js.erb
$("#pin_<%= @pin.id %>_likes").html("<%=j render partial: "pins/likes", locals: {pin: @pin} %>");

app/views/pins/likes/destroy.js.erb
$("#pin_<%= @pin.id %>_likes").html("<%=j render partial: "pins/likes", locals: {pin: @pin} %>");

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
	%h1 New Form

	= render 'form'

	= link_to 'Back' , root_path

app/views/pins/show.html.haml
#pin_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.pin_image
				= image_tag @pin.image.url
			.panel-body
				%h1= @pin.title
				%p.description= @pin.description
			.panel-footer
				.row
					.col-md-6
						%p.user
							Posted by
							= @pin.user.profile_name
					.col-md-6
						.btn-group.pull-right
							= link_to 'Back' , root_path , class: "btn btn-default" , data: {disable_with: "<i class='fa fa-spinner fa-spin'></i>  going back.."}
							- if @pin.user == current_user 
								= link_to "Edit", edit_pin_path, class: "btn btn-default"
								= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"
.container#likeem
	.row
		.col-md-6
			%p= "Likes this post:"
			= render 'likers'